tutorial/konferencje/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("dodaj/<str:name>/", views.dodaj, name="dodaj"),
    path("edytuj/<str:name>/<str:title>/", views.edytuj, name="edytuj")
]

tutorial/polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote")
]

tutorial/tutorial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include("polls.urls")),
    path('komentarze/', include("komentarze.urls"))
]

tutorial/konferencje/models.py
from django.db import models

# Create your models here.


class Conference(models.Model):
	name = models.CharField(max_length=200, unique=True)
	place = models.CharField(max_length=500)
	start_date = models.DateField()
	end_date = models.DateField()
	abstract_deadline = models.DateField()

	def __str__(self):
		return f"{self.name}"

class Abstract(models.Model):
	conference = models.ForeignKey(Conference, on_delete=models.PROTECT) 
	title = models.CharField(max_length=200, unique=True)
	text = models.TextField()
	type_a = models.CharField(max_length=200,choices=[("PLAKAT", "PLAKAT"), ("REFERAT", "REFERAT"), ("REFERAT LUB PLAKAT", "REFERAT LUB PLAKAT")])
	author = models.CharField(max_length=200)
	affiliation = models.CharField(max_length=500)

	def __str__(self):
		return f"{self.title}"


tutorial/konferencje/forms.py
from django.forms import ModelForm
from .models import Abstract

class AbstractForm(ModelForm):
	class Meta:
		model = Abstract
		fields = ["title","text", "type_a","author", "affiliation"]

tutorial/konferencje/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.

from .models import Conference, Abstract
from django.utils import timezone
from .forms import AbstractForm

def home(request):
	all_conferences = Conference.objects.all()
	all_abstracts = Abstract.objects.all()
	today = timezone.now().date()
	return render(request, 'konferencje/Konferencje.html', {'all_conferences': all_conferences, 'today':today,
		'all_abstracts':all_abstracts})

def dodaj(request, name):

	if request.method == 'POST':
		form = AbstractForm(request.POST)

		if form.valid():
			conference = Conference.objectc.get(name = name)

			abstract = form.save(commit=False)
			abstract.conference = conference
			abstract.save()

	else:
		form = AbstractForm()


	return render(request, 'konferencje/Dodaj.html', {'form':form, 'name':name})

def edytuj(request, name ,title):
	abstract = get_object_or_404(Abstract, title=title)

	if request.method == 'POST':
		form = AbstractForm(request.POST, instance=abstract)

		if form.is_valid():
			form.save()

	else:
		form = AbstractForm(instance=abstract)

	return render(request, 'konferencje/Edytuj.html', {'form':form, 'name':name,'title': title})

tutorial/konferencje/templates/konferencje/Dodaj.html
<!doctype html>

	<head>
		
		<title>Dodaj abstrakt</title>
		<style type="text/css">
			.abs{
				padding: 5px;
				margin: 5px;
			}
		</style>
	</head>

	<body>
		
		<div>
			
			<div>
				<h1>Dodaj abstrakt do konferencji - "{{name}}"</h1>
			</div>
			<div>
				<form method='post'>
					{% csrf_token %}
                        <div class='abs'>
                        	<label for="id_title">Tytuł</label>
                            <div>{{form.title}}</div>
                        </div>
                        <div class='abs'>
                            <label for="id_text">Tekst</label>
                            <div>{{form.text}}</div>
                        </div>
                        <div class='abs'>
                            <label for="id_typ_a">Typ abstraktu</label>
                            <div>{{form.type_a}}</div>
                        </div>
                        <div class='abs'>
                            <label for="id_author">Autor</label>
                            <div>{{form.author}}</div>
                        </div>
                        <div class='abs'>
                            <label for="id_affiliation">Afiliacja</label>
                            <div>{{form.affiliation}}</div>
                        </div>                       
					<button type="submit">Zatwierdź</button>
				</form>

			</div>
		</div>
	</body>

tutorial/konferencje/templates/konferencje/Edytuj.html
<!doctype html>
	<head>
		<title>Edytuj abstrakt</title>
	</head>
	<body>
		<div>
			<h1>Edytuj abstrakt - "{{title}}"</h1>
		</div>

		<div>
				<form method='post'>
					{% csrf_token %}
                        <div class='abs'>
                        	<label for="id_title">Tytuł</label>
                            <div>{{form.title}}</div>
                        </div>
                        <div class='abs'>
                            <label for="id_text">Tekst</label>
                            <div>{{form.text}}</div>
                        </div>
                        <div class='abs'>
                            <label for="id_typ_a">Typ abstraktu</label>
                            <div>{{form.type_a}}</div>
                        </div>
                        <div class='abs'>
                            <label for="id_author">Autor</label>
                            <div>{{form.author}}</div>
                        </div>
                        <div class='abs'>
                            <label for="id_affiliation">Afiliacja</label>
                            <div>{{form.affiliation}}</div>
                        </div>                       
					<button type="submit">Zatwierdź</button>
				</form>

			</div>
	</body>

tutorial/konferencje/templates/konferencje/Konferencje.html
<!doctype html>

	<head>
		<title>Konferencje</title>
		<style type="text/css">
			th, td{
				padding: 20px;
				text-align: center;
			}
		</style>
	</head>

	<body>
		
	<div>
		<div>
			<h1>Konferencje naukowe - Universe of biology</h1>
		</div>
        <div>
        <table>
            <thead>
                <tr>
                    <th>Nazwa</th>
                    <th>Miejsce</th>
                    <th>Data rozpoczęcia</th>
                    <th>Data zakończenia</th>
                    <th>Deadline na abstrakty</th>
                    <th>Dodaj</th>
                    <th>Edytuj</th>
                </tr>
            </thead>
            <tbody>

                {% for conf in all_conferences %}
                <tr>
                    <td>{{ conf.name }}</td>
                    <td>{{ conf.place }}</td>
                    <td > {{ conf.start_date }} </td>
                    <td >{{ conf.end_date }}</td>
                    <td>{{ conf.abstract_deadline }}</td>
                    <td >{% if conf.abstract_deadline >= today %}
                    	<a href = "{% url 'dodaj' conf.name %}"><button>Dodaj abstrakt</button></a>
                    	{% else %}
                    	<p>Termin zgłoszeń minął</p>
                    	{% endif %}
                    </td>
                    <td >{% if conf.abstract_deadline >= today %}
                    		{% for abstract in conf.abstract_set.all %}
                    		<a href="{% url 'edytuj' conf.name abstract.title %}">{{abstract.title}}</a>
                    		{% endfor %}
                    	{% else %}
                    	<p>Termin edycji minął</p>
                    	{% endif %}
                    </td>
                </tr>
                {% endfor %}

            </tbody>
        </table>
        </div>
    </div>

	</body>